// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: effective_msg.proto
// Protobuf C++ Version: 7.36.0-dev

#include "effective_msg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
class EffectiveMsg::_Internal {
 public:
  using HasBits = decltype(::std::declval<EffectiveMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_._has_bits_);
};

constexpr EffectiveMsg::ParseTableT_ EffectiveMsg::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_._has_bits_),
      0, // no _extensions_
      8, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967040,  // skipmap
      offsetof(ParseTableT_, field_entries),
      8,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallbackLite,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::EffectiveMsg>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string log_info = 8;
      {::_pbi::TcParser::FastUS1,
       {66, 2, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.log_info_)}},
      // int32 level = 1;
      {::_pbi::TcParser::FastV32S1,
       {8, 4, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.level_)}},
      // int64 timestamp = 2;
      {::_pbi::TcParser::FastV64S1,
       {16, 3, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.timestamp_)}},
      // int32 pid = 3;
      {::_pbi::TcParser::FastV32S1,
       {24, 5, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.pid_)}},
      // int32 tid = 4;
      {::_pbi::TcParser::FastV32S1,
       {32, 6, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.tid_)}},
      // int32 line = 5;
      {::_pbi::TcParser::FastV32S1,
       {40, 7, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.line_)}},
      // string file_name = 6;
      {::_pbi::TcParser::FastUS1,
       {50, 0, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.file_name_)}},
      // string func_name = 7;
      {::_pbi::TcParser::FastUS1,
       {58, 1, 0,
        PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.func_name_)}},
    }}, {{
      65535, 65535
    }}, {{
      // int32 level = 1;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.level_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int64 timestamp = 2;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.timestamp_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
      // int32 pid = 3;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.pid_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 tid = 4;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.tid_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // int32 line = 5;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.line_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
      // string file_name = 6;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.file_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string func_name = 7;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.func_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string log_info = 8;
      {PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.log_info_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\14\0\0\0\0\0\11\11\10\0\0\0\0\0\0\0"
      "EffectiveMsg"
      "file_name"
      "func_name"
      "log_info"
    }},
  };
}


inline constexpr EffectiveMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : file_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        func_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        log_info_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::int64_t{0}},
        level_{0},
        pid_{0},
        tid_{0},
        line_{0} {}

template <typename>
constexpr EffectiveMsg::EffectiveMsg(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::MessageLite(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL EffectiveMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) EffectiveMsg(arena);
}
constexpr auto EffectiveMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(EffectiveMsg), alignof(EffectiveMsg));
}
constexpr auto EffectiveMsg::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &EffectiveMsg::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<EffectiveMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &EffectiveMsg::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<EffectiveMsg>(), &EffectiveMsg::ByteSizeLong,
              &EffectiveMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_._cached_size_),
          true,
      },
      "EffectiveMsg",
  };
}
struct EffectiveMsgGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr EffectiveMsgGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 EffectiveMsg_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(EffectiveMsg::InternalGenerateClassData_(
            _default, &EffectiveMsg_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<EffectiveMsg>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~EffectiveMsgGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) EffectiveMsg _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<EffectiveMsg>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(EffectiveMsgGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST EffectiveMsgGlobalsTypeInternal EffectiveMsg_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* EffectiveMsg_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return EffectiveMsg_globals_.GetClassData();
#else
  return EffectiveMsg_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
// ===================================================================

EffectiveMsg::EffectiveMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, EffectiveMsg_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:EffectiveMsg)
}
PROTOBUF_NDEBUG_INLINE EffectiveMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::EffectiveMsg& from_msg)
      : _has_bits_{from._has_bits_},
        file_name_(arena, from.file_name_),
        func_name_(arena, from.func_name_),
        log_info_(arena, from.log_info_) {}

EffectiveMsg::EffectiveMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const EffectiveMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, EffectiveMsg_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  EffectiveMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, line_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::line_));

  // @@protoc_insertion_point(copy_constructor:EffectiveMsg)
}
PROTOBUF_NDEBUG_INLINE EffectiveMsg::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : file_name_(arena),
        func_name_(arena),
        log_info_(arena) {}

inline void EffectiveMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, line_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::line_));
}
EffectiveMsg::~EffectiveMsg() {
  // @@protoc_insertion_point(destructor:EffectiveMsg)
  SharedDtor(*this);
}
inline void EffectiveMsg::SharedDtor(MessageLite& self) {
  EffectiveMsg& this_ = static_cast<EffectiveMsg&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.file_name_.Destroy();
  this_._impl_.func_name_.Destroy();
  this_._impl_.log_info_.Destroy();
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite EffectiveMsg_class_data_ =
    EffectiveMsg::InternalGenerateClassData_(EffectiveMsg_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EffectiveMsg::GetClassData() const {
  return EffectiveMsg_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
EffectiveMsg::GetClassData() const {
  return EffectiveMsg_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const EffectiveMsg::ParseTableT_
    EffectiveMsg::_table_ =
        EffectiveMsg::InternalGenerateParseTable_(EffectiveMsg_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void EffectiveMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:EffectiveMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.file_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.func_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.log_info_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f8U)) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.line_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.line_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL EffectiveMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const EffectiveMsg& this_ = static_cast<const EffectiveMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL EffectiveMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const EffectiveMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:EffectiveMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 level = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_level() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_level(), target);
    }
  }

  // int64 timestamp = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_timestamp() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_timestamp(), target);
    }
  }

  // int32 pid = 3;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_pid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_pid(), target);
    }
  }

  // int32 tid = 4;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_tid() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
              stream, this_._internal_tid(), target);
    }
  }

  // int32 line = 5;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_line() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
              stream, this_._internal_line(), target);
    }
  }

  // string file_name = 6;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_file_name().empty()) {
      const ::std::string& _s = this_._internal_file_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EffectiveMsg.file_name");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // string func_name = 7;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_func_name().empty()) {
      const ::std::string& _s = this_._internal_func_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EffectiveMsg.func_name");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // string log_info = 8;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_log_info().empty()) {
      const ::std::string& _s = this_._internal_log_info();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "EffectiveMsg.log_info");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EffectiveMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t EffectiveMsg::ByteSizeLong(const MessageLite& base) {
  const EffectiveMsg& this_ = static_cast<const EffectiveMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t EffectiveMsg::ByteSizeLong() const {
  const EffectiveMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:EffectiveMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string file_name = 6;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_file_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_file_name());
      }
    }
    // string func_name = 7;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_func_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_func_name());
      }
    }
    // string log_info = 8;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_log_info().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_log_info());
      }
    }
    // int64 timestamp = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // int32 level = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_level() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_level());
      }
    }
    // int32 pid = 3;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_pid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_pid());
      }
    }
    // int32 tid = 4;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_tid() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_tid());
      }
    }
    // int32 line = 5;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_line() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_line());
      }
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void EffectiveMsg::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<EffectiveMsg*>(&to_msg);
  auto& from = static_cast<const EffectiveMsg&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:EffectiveMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_file_name().empty()) {
        _this->_internal_set_file_name(from._internal_file_name());
      } else {
        if (_this->_impl_.file_name_.IsDefault()) {
          _this->_internal_set_file_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_func_name().empty()) {
        _this->_internal_set_func_name(from._internal_func_name());
      } else {
        if (_this->_impl_.func_name_.IsDefault()) {
          _this->_internal_set_func_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_log_info().empty()) {
        _this->_internal_set_log_info(from._internal_log_info());
      } else {
        if (_this->_impl_.log_info_.IsDefault()) {
          _this->_internal_set_log_info("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_level() != 0) {
        _this->_impl_.level_ = from._impl_.level_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_pid() != 0) {
        _this->_impl_.pid_ = from._impl_.pid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_tid() != 0) {
        _this->_impl_.tid_ = from._impl_.tid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_line() != 0) {
        _this->_impl_.line_ = from._impl_.line_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void EffectiveMsg::CopyFrom(const EffectiveMsg& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:EffectiveMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void EffectiveMsg::InternalSwap(EffectiveMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_name_, &other->_impl_.file_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.func_name_, &other->_impl_.func_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_info_, &other->_impl_.log_info_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.line_)
      + sizeof(EffectiveMsg::_impl_.line_)
      - PROTOBUF_FIELD_OFFSET(EffectiveMsg, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
