// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: effective_msg.proto
// Protobuf C++ Version: 7.36.0-dev

#ifndef effective_5fmsg_2eproto_2epb_2eh
#define effective_5fmsg_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7036000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_effective_5fmsg_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_effective_5fmsg_2eproto {
  static const ::uint32_t offsets[];
};
class EffectiveMsg;
struct EffectiveMsgGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern EffectiveMsgGlobalsTypeInternal EffectiveMsg_globals_;
extern const ::google::protobuf::internal::ClassDataLite EffectiveMsg_class_data_;
#else
extern const EffectiveMsgGlobalsTypeInternal EffectiveMsg_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED EffectiveMsg final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:EffectiveMsg) */ {
 public:
  inline EffectiveMsg() : EffectiveMsg(nullptr) {}
  ~EffectiveMsg() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EffectiveMsg* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EffectiveMsg));
  }
#endif

  template <typename = void>
  explicit constexpr EffectiveMsg(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline EffectiveMsg(const EffectiveMsg& from) : EffectiveMsg(nullptr, from) {}
  inline EffectiveMsg(EffectiveMsg&& from) noexcept : EffectiveMsg(nullptr, ::std::move(from)) {}
  inline EffectiveMsg& operator=(const EffectiveMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline EffectiveMsg& operator=(EffectiveMsg&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const EffectiveMsg& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<EffectiveMsg>(&EffectiveMsg_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(EffectiveMsg& a, EffectiveMsg& b) { a.Swap(&b); }
  inline void Swap(EffectiveMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EffectiveMsg* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] EffectiveMsg* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<EffectiveMsg>(arena);
  }
  void CopyFrom(const EffectiveMsg& from);
  void MergeFrom(const EffectiveMsg& from) { EffectiveMsg::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EffectiveMsg* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "EffectiveMsg"; }

  explicit EffectiveMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  EffectiveMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const EffectiveMsg& from);
  EffectiveMsg(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, EffectiveMsg&& from) noexcept
      : EffectiveMsg(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFileNameFieldNumber = 6,
    kFuncNameFieldNumber = 7,
    kLogInfoFieldNumber = 8,
    kTimestampFieldNumber = 2,
    kLevelFieldNumber = 1,
    kPidFieldNumber = 3,
    kTidFieldNumber = 4,
    kLineFieldNumber = 5,
  };
  // string file_name = 6;
  void clear_file_name() ;
  [[nodiscard]] const ::std::string& file_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_file_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_file_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_file_name();
  void set_allocated_file_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_file_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_file_name();

  public:
  // string func_name = 7;
  void clear_func_name() ;
  [[nodiscard]] const ::std::string& func_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_func_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_func_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_func_name();
  void set_allocated_func_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_func_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_func_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_func_name();

  public:
  // string log_info = 8;
  void clear_log_info() ;
  [[nodiscard]] const ::std::string& log_info() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_log_info(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_log_info();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_log_info();
  void set_allocated_log_info(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_log_info() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_log_info(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_log_info();

  public:
  // int64 timestamp = 2;
  void clear_timestamp() ;
  [[nodiscard]] ::int64_t timestamp() const;
  void set_timestamp(::int64_t value);

  private:
  ::int64_t _internal_timestamp() const;
  void _internal_set_timestamp(::int64_t value);

  public:
  // int32 level = 1;
  void clear_level() ;
  [[nodiscard]] ::int32_t level() const;
  void set_level(::int32_t value);

  private:
  ::int32_t _internal_level() const;
  void _internal_set_level(::int32_t value);

  public:
  // int32 pid = 3;
  void clear_pid() ;
  [[nodiscard]] ::int32_t pid() const;
  void set_pid(::int32_t value);

  private:
  ::int32_t _internal_pid() const;
  void _internal_set_pid(::int32_t value);

  public:
  // int32 tid = 4;
  void clear_tid() ;
  [[nodiscard]] ::int32_t tid() const;
  void set_tid(::int32_t value);

  private:
  ::int32_t _internal_tid() const;
  void _internal_set_tid(::int32_t value);

  public:
  // int32 line = 5;
  void clear_line() ;
  [[nodiscard]] ::int32_t line() const;
  void set_line(::int32_t value);

  private:
  ::int32_t _internal_line() const;
  void _internal_set_line(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:EffectiveMsg)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<3, 8,
                          0, 55,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const EffectiveMsg& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr file_name_;
    ::google::protobuf::internal::ArenaStringPtr func_name_;
    ::google::protobuf::internal::ArenaStringPtr log_info_;
    ::int64_t timestamp_;
    ::int32_t level_;
    ::int32_t pid_;
    ::int32_t tid_;
    ::int32_t line_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_effective_5fmsg_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// EffectiveMsg

// int32 level = 1;
inline void EffectiveMsg::clear_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
inline ::int32_t EffectiveMsg::level() const {
  // @@protoc_insertion_point(field_get:EffectiveMsg.level)
  return _internal_level();
}
inline void EffectiveMsg::set_level(::int32_t value) {
  _internal_set_level(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:EffectiveMsg.level)
}
inline ::int32_t EffectiveMsg::_internal_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.level_;
}
inline void EffectiveMsg::_internal_set_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.level_ = value;
}

// int64 timestamp = 2;
inline void EffectiveMsg::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::int64_t{0};
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
inline ::int64_t EffectiveMsg::timestamp() const {
  // @@protoc_insertion_point(field_get:EffectiveMsg.timestamp)
  return _internal_timestamp();
}
inline void EffectiveMsg::set_timestamp(::int64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:EffectiveMsg.timestamp)
}
inline ::int64_t EffectiveMsg::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void EffectiveMsg::_internal_set_timestamp(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// int32 pid = 3;
inline void EffectiveMsg::clear_pid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pid_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
inline ::int32_t EffectiveMsg::pid() const {
  // @@protoc_insertion_point(field_get:EffectiveMsg.pid)
  return _internal_pid();
}
inline void EffectiveMsg::set_pid(::int32_t value) {
  _internal_set_pid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:EffectiveMsg.pid)
}
inline ::int32_t EffectiveMsg::_internal_pid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pid_;
}
inline void EffectiveMsg::_internal_set_pid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pid_ = value;
}

// int32 tid = 4;
inline void EffectiveMsg::clear_tid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tid_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
}
inline ::int32_t EffectiveMsg::tid() const {
  // @@protoc_insertion_point(field_get:EffectiveMsg.tid)
  return _internal_tid();
}
inline void EffectiveMsg::set_tid(::int32_t value) {
  _internal_set_tid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:EffectiveMsg.tid)
}
inline ::int32_t EffectiveMsg::_internal_tid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tid_;
}
inline void EffectiveMsg::_internal_set_tid(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tid_ = value;
}

// int32 line = 5;
inline void EffectiveMsg::clear_line() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_ = 0;
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
}
inline ::int32_t EffectiveMsg::line() const {
  // @@protoc_insertion_point(field_get:EffectiveMsg.line)
  return _internal_line();
}
inline void EffectiveMsg::set_line(::int32_t value) {
  _internal_set_line(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:EffectiveMsg.line)
}
inline ::int32_t EffectiveMsg::_internal_line() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.line_;
}
inline void EffectiveMsg::_internal_set_line(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.line_ = value;
}

// string file_name = 6;
inline void EffectiveMsg::clear_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline const ::std::string& EffectiveMsg::file_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:EffectiveMsg.file_name)
  return _internal_file_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EffectiveMsg::set_file_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.file_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:EffectiveMsg.file_name)
}
inline ::std::string* PROTOBUF_NONNULL EffectiveMsg::mutable_file_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:EffectiveMsg.file_name)
  return _s;
}
inline const ::std::string& EffectiveMsg::_internal_file_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.file_name_.Get();
}
inline void EffectiveMsg::_internal_set_file_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.file_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EffectiveMsg::_internal_mutable_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.file_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EffectiveMsg::release_file_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:EffectiveMsg.file_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.file_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.file_name_.Set("", GetArena());
  }
  return released;
}
inline void EffectiveMsg::set_allocated_file_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.file_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.file_name_.IsDefault()) {
    _impl_.file_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:EffectiveMsg.file_name)
}

// string func_name = 7;
inline void EffectiveMsg::clear_func_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.func_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
inline const ::std::string& EffectiveMsg::func_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:EffectiveMsg.func_name)
  return _internal_func_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EffectiveMsg::set_func_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.func_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:EffectiveMsg.func_name)
}
inline ::std::string* PROTOBUF_NONNULL EffectiveMsg::mutable_func_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_func_name();
  // @@protoc_insertion_point(field_mutable:EffectiveMsg.func_name)
  return _s;
}
inline const ::std::string& EffectiveMsg::_internal_func_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.func_name_.Get();
}
inline void EffectiveMsg::_internal_set_func_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.func_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EffectiveMsg::_internal_mutable_func_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.func_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EffectiveMsg::release_func_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:EffectiveMsg.func_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.func_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.func_name_.Set("", GetArena());
  }
  return released;
}
inline void EffectiveMsg::set_allocated_func_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.func_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.func_name_.IsDefault()) {
    _impl_.func_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:EffectiveMsg.func_name)
}

// string log_info = 8;
inline void EffectiveMsg::clear_log_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_info_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
inline const ::std::string& EffectiveMsg::log_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:EffectiveMsg.log_info)
  return _internal_log_info();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void EffectiveMsg::set_log_info(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.log_info_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:EffectiveMsg.log_info)
}
inline ::std::string* PROTOBUF_NONNULL EffectiveMsg::mutable_log_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_log_info();
  // @@protoc_insertion_point(field_mutable:EffectiveMsg.log_info)
  return _s;
}
inline const ::std::string& EffectiveMsg::_internal_log_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.log_info_.Get();
}
inline void EffectiveMsg::_internal_set_log_info(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_info_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL EffectiveMsg::_internal_mutable_log_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.log_info_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE EffectiveMsg::release_log_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:EffectiveMsg.log_info)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.log_info_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.log_info_.Set("", GetArena());
  }
  return released;
}
inline void EffectiveMsg::set_allocated_log_info(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.log_info_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.log_info_.IsDefault()) {
    _impl_.log_info_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:EffectiveMsg.log_info)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // effective_5fmsg_2eproto_2epb_2eh
